server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attendanceService
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: attendance-service

logging:
  level:
    org.springframework.web: DEBUG

