server:
  port: 8088

spring:
  application:
    name: scheduler-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: satheeshprabhu012@gmail.com
    password: ghbn aoyr qipm nimi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


cron:
  payroll: "0 5 0 1 * ?"
  attendance:
    daily: "0 0 18 * * ?"
    weekly: "0 0 8 ? * MON"
  reminders:
    leaves: "0 0 9-18 ? * MON-FRI"

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG


